version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_turnos_1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: