-- MySQL Script generated by MySQL Workbench
-- Thu Jan  2 19:10:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Proyecto_Reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_Reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_Reservas` DEFAULT CHARACTER SET utf8mb3 ;
USE `Proyecto_Reservas` ;

-- -----------------------------------------------------
-- Table `Proyecto_Reservas`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Reservas`.`servicios` (
  `idservicios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` FLOAT NOT NULL,
  `duracion` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idservicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Proyecto_Reservas`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Reservas`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rol` ENUM('client', 'admin') NOT NULL DEFAULT 'client',
  `active` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Proyecto_Reservas`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Reservas`.`turnos` (
  `idturnos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `servicios_idservicios` INT NOT NULL,
  PRIMARY KEY (`idturnos`),
  INDEX `fk_user_turnos_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_servicios_turnos_idx` (`servicios_idservicios` ASC) VISIBLE,
  CONSTRAINT `fk_servicios_turnos`
    FOREIGN KEY (`servicios_idservicios`)
    REFERENCES `Proyecto_Reservas`.`servicios` (`idservicios`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_user_turnos`
    FOREIGN KEY (`user_id`)
    REFERENCES `Proyecto_Reservas`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;